### ISSUE TITLE
Finish 0:00 - 25:00 for HTML Crash Course

### ISSUE THREAD

**Issue by regmi2** [Uhhkash/HTML_CSS_INTRO#2]
https://www.youtube.com/watch?v=qz0aGYrrlhU&pp=ygUuaHRtbCB0dXRvcmlhbCBmb3IgYmVnaW5uZXJzOiBIVE1MIENyYXNoIENvdXJzZQ%3D%3D

- [ ] Take Notes of Each Chapter Section
- [ ] Prepare to "Teach" Pallav about it 
- [ ] Write down questions (here, in a google doc, wherever)

**Comment by regmi2** [comment]
#Title 

## Chapter 1

**Comment by Uhhkash** [comment]
Need help pushing to github

**Comment by regmi2** [comment]
Went through how to use Command line interface (CLI) to push local changes to GitHub Online Repo

Todo 

- [ ] Go through Notes
- [ ] Have Aakash teach me the concepts
- [ ] - [ ] Have a conversation about concepts that might be important to acknowledge within the content
